# yaml-language-server: $schema=https://squidfunk.github.io/mkdocks-material/schema.json
site_name: PyTexas Foundation
repo_url: https://github.com/pytexas/pytexas.github.io
repo_name: pytexas/pytexas.github.io
site_url: https://pytexas.org
site_author: PyTexas Foundation <foundation@pytexas.org>
site_description: The PyTexas Foundation is a non-profit dedicated to educating engineers about Python in the state of Texas
copyright: 'PyTexas Foundation Â© 2014 - 2025'
theme:
  name: material
  custom_dir: docs/overrides
  locale: en
  logo: assets/images/logo.png
  favicon: assets/images/favicon.png
  features:
    - announce.dismiss
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - toc.follow
  palette:
    - scheme: default
      primary: blue
      accent: amber
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: yellow
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode
nav:
  - Home: index.md
  - Foundation:
      - 'About the Foundation': foundation/about.md
      - 'Who we are': foundation/who.md
      - Governance: foundation/governance.md
      - 'Meeting minutes': foundation/minutes.md
      - Fundraising: foundation/fundraising.md
      - Sponsors: foundation/sponsors.md
      - Privacy: privacy.md
  - Blog:
      - blog/index.md
  - Conference: conference.md
  - Meetup: meetup-info.md
  - Sponsorship:
    - Our Programs: sponsorship/index.md 
    - Friends of PyTexas: sponsorship/friends.md
    - Meetup: sponsorship/meetup.md
    - Conference: sponsorship/conference.md
    - Charitable Contribution: sponsorship/charitable.md
markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true
plugins:
  - search
  - social
  - blog:
      blog_dir: blog
      blog_toc: true
      post_url_format: "{slug}"
  - redirects:
      redirect_maps:
        'discord.md': 'https://discord.gg/jNPAbcNukj'
        'friends.md': 'sponsorship/friends.md'
        'links.md': 'https://linktr.ee/pytexas'
        'newsletter.md': 'https://mailchi.mp/035388afb48a/pytexas-community'
        '2019.md': 'https://2019.pytexas.org'
        '2017.md': 'https://2017.pytexas.org'
        '2012.md': 'https://web.archive.org/web/20121119035342/http://www.pytexas.org/2012/'
        '2011.md': 'https://web.archive.org/web/20110923123355/http://www.pytexas.org/2011/'
        '2010.md': 'https://web.archive.org/web/20100820002737/http://pytexas.org/PyTexasHome'
        '2009.md': 'https://web.archive.org/web/20091115065924/http://pycamp.python.org/Texas/HomePage'
        '2008.md': 'https://web.archive.org/web/20081218000930/http://scipy.org/TXUncon2008'
        '2007.md': 'https://web.archive.org/web/20071212120001/http://pycamp.python.org/Texas/HomePage'

extra:
  status:
    new: Recently added
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/pytexas
      name: Twitter
    - icon: fontawesome/brands/mastodon
      link: https://fosstodon.org/@pytexas
      name: Mastodon
    - icon: fontawesome/brands/discord
      link: https://discord.gg/jNPAbcNukj
      name: Discord
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/pytexas-foundation
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/pytexas
    - icon: fontawesome/brands/meetup
      link: https://www.meetup.com/pytexas-virtual-meetup/
    - icon: fontawesome/brands/github
      link: https://github.com/pytexas
